name: github pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: log untrusted output
      run: |
        echo "::stop-commands::`echo -n ${{ github.token }} | sha256sum | head -c 64`"
        echo "untrusted output"
        echo "::`echo -n ${{ github.token }} | sha256sum | head -c 64`::"
    
    - uses: actions/checkout@v2
      with: 
        submodules: true

    - name: Hugo setup
      uses: peaceiris/actions-hugo@v2.4.13
      with:
        hugo-version: '0.76.5'

    - name: Build
      run: hugo

    - name: Deploy
      uses: peaceiris/actions-github-pages@v3.1.12
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}  
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: ./public
