name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Hugo setup
      uses: peaceiris/actions-hugo@v3.0.0
      with:
        hugo-version: '0.122.0'

    - name: Build
      run: hugo

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4.0.0
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: ./public
